export const experienceData = [
  {
    start: "Mar 2021",
    end: "Sept 2021",
    title: "Software Development Engineer",
    company: "Listee",
    type: "full-time",
    stories: [
      "Successfully built a custom named entity recognition pipeline with spaCy to automate parsing of resumes for profile creation. Combined pipeline with Emsi Skill API to extract skills and provide to HR a description of each skill.",
      "Designed the fullstack framework for automatic account creation using FastAPI, React, and MongoDB.",
      "Used Redux architecture and Immutable.js with React to manage the state of our UI components.",
      "Migrated to Typescript to improve readability and debugging in the codebase.",
      "Used Fetch API and Axios to store resume data into Redux, improving data accessibility for UI components.",
      "Improved performance of web application by memoizing the code with React hooks.",
      "Used Scrum Agile Methodology in my work with the addition of Jira for sprint backlog.",
    ],
  },
  {
    start: "May 2021",
    end: "Aug 2021",
    title: "Software Development Engineer, Intern",
    company: "Zecstra",
    type: "full-time",
    stories: [
      "Built a visual analytics dashboard displaying stakeholder's datasets using D3.js-based React libraries.",
      "Developed a microfrontend architecture with Single SPA to easily manage individual applications and improve initial loading time.  Provide developers the flexibility to use multiple frameworks for each microfrontend.",
      "Implemented backend with Django and RESTful API to stream data to the frontend for dynamic data visualizations.",
      "Enhanced UX by building a custom settings menu for each data visualization, allowing users to manipulate the datasets.",
      "Optimized tabular data rendering with React-Windows, reducing number of elements that get rendered in the DOM.",
      "Integrated Redux architecture into our web application to manage the state of our components.",
      "Provided design direction and iterated with CEO and quality reps to create beautifully functional experiences.",
      "Debugged application with Lighthouse and React DevTools to improve quality and performance for each page.",
    ],
  },
  {
    start: "Sept 2020",
    end: "Pre",
    title: "RL Research Assistant",
    company: "Resilient Cyber-Physical Systems",
    type: "full-time",
    stories: [
      "Revamp the neural network controller to achieve safe training using proximal policy optimization.",
      "Apply policy-gradient algorithms to guarantee safety during the learning and execution phase.",
      "Integrated methods in OpenAI’s Safety Gym simulator for performance measure and debugging.",
      "Researched variants of policy gradient algorithms such as PPO, TRPO, DDPG  with constraints and their application to safety reinforcement learning.",
    ],
  },
  {
    start: "Sept 2019",
    end: "Pre",
    title: "Executive Board",
    company: "Institute of Electrical and Eletronics Engineering",
    type: "full-time",
    stories: [
      "Led a team of engineers at UCI to provide students opportunities to leverage their technical skills and build their professional portfolios.",
      "Coordinated with project coordinators in organizing PCB and deep learning workshops.",
      "Coordinated with industry correspondents connect with industries and successfully brought in professional engineers for networking events.",
      "Cofounded IEEE Students United and Spearheaded statewide collaboration with region 6 IEEE branches; aimed to help students gain valuable engineering skills through a virtual environment.",
      "Collaborated with a maker lab to organize a state-wide robotics program and led the technical program. Successfully earned $1500 in funding from IEEE.",
    ],
  },
];
